#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.75.216.231:3306/educloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.zsc.edu.entity
  mapperLocations: classpath:mappers/*.xml
